# Generated by Django 4.2.30 on 2026-09-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('poultry_type', models.CharField(choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('SONALI', 'Sonali'), ('OTHER', 'Other')], max_length=10)),
                ('start_date', models.DateField()),
                ('initial_bird_count', models.PositiveIntegerField()),
                ('purchase_price_per_bird', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='poultry.farm')),
            ],
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('farm', 'code'), name='unique_batch_code_per_farm'),
        ),
    ]
