# Generated by Django 4.2.30 on 2026-09-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_batch_batch_unique_batch_code_per_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('POULTRY', 'Poultry'), ('EGG', 'Egg')], max_length=10)),
                ('unit', models.CharField(choices=[('BIRD', 'Bird'), ('EGG', 'Egg')], max_length=5)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='poultry.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='poultry.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FARM', 'Farm'), ('BATCH', 'Batch')], max_length=5)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='poultry.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='poultry.farm')),
            ],
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('egg_count', models.PositiveIntegerField()),
                ('damaged_egg_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='poultry.batch')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('feed_amount_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dead_count', models.PositiveIntegerField(default=0)),
                ('sick_count', models.PositiveIntegerField(default=0)),
                ('medicine_used', models.BooleanField(default=False)),
                ('medicine_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='poultry.batch')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eggproduction',
            constraint=models.UniqueConstraint(fields=('batch', 'production_date'), name='unique_egg_production_per_batch_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('batch', 'record_date'), name='unique_daily_record_per_batch_date'),
        ),
    ]
